stages:
    - mirror

include:
  - project: 'proton/fe/proton-config'
    ref: master
    file: '/_templates-ci/config.gitlab-ci.yml'

sync-app:
    cache: {}
    stage: mirror
    tags:
        - experimental
      # use special keywords
    only:
        refs:
          - tags
          - master

    script:
        - git clone "$APP_GIT_CI" --depth 1 --branch master _APP_CLONE;
        - cd _APP_CLONE
        - git fetch
        - git remote add public git@github.com:dhoko/synctest.git
        - git remote -v
        - echo 'CURRENT BRANCH'
        - git rev-parse --abbrev-ref HEAD
        - echo
        - git checkout master
        - git push public master
        - git push public "$(git describe --abbrev=0)"
