stages:
    - sync

include:
  - project: 'proton/fe/proton-config'
    ref: master
    file: '/_templates-ci/public.gitlab-ci.yml'


sync-app
    cache: {}
    stage: sync
    tags:
        - experimental
      # use special keywords
    only:
        - tags
        - /^master$/
    # use special keyword
    except:
      - branches
    script:
        - git remote add-url public git@github.com:dhoko/synctest.git
        - git push public master
        - git push public "$(git describe --abbrev=0)"
    dependencies: []
