stages:
    - setup
    - test
    - i18n
    - deploy
    - rpm
    - menache
    - bot

include:
  - project: 'proton/fe/proton-config'
    ref: master
    file: '/_templates-ci/public.gitlab-ci.yml'

variables:
    APP_GIT: git@gitlab.protontech.ch:dhoko/protonvpn-settings.git
    NODE_OPTIONS: --max-old-space-size=4096

i18n-auto-pull:
    cache: {}
    stage: bot
    tags:
        - experimental
    only:
        - schedules
    script:
        - ./ci-scripts/prepare-ci.sh i18n upgrade-app --sync-config protonvpn/webapp
    dependencies: []
