stages:
    - mirror

include:
  - project: 'proton/fe/proton-config'
    ref: master
    file: '/_templates-ci/config.gitlab-ci.yml'

sync-app:
    cache: {}
    stage: mirror
    tags:
        - experimental
      # use special keywords
    only:
        refs:
          - tags
          - master

    script:
        - git remote add public git@github.com:dhoko/synctest.git
        - git push public master -f
        - git push public "$(git describe --abbrev=0)"
