stages:
    - build
    - mirror
    - public-release

default:
    image: ubuntu:latest
    before_script:
     - apt-get -y update
     - apt-get install -y connect-proxy git unzip curl jq
     - 'which ssh-agent || apt-get -y install openssh-client'
     - eval $(ssh-agent -s)
     - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
     - git config --global user.email $GIT_CI_EMAIL
     - git config --global user.name $GIT_CI_USERNAME
     - git config --global url."https://".insteadOf git://
     - mkdir ~/.ssh 2> /dev/null
     - |
       cat <<EOF > ~/.ssh/config
       Host github.com
           Hostname ssh.github.com
           User git
           Port 443
           ProxyCommand connect-proxy -H $http_proxy %h %p
       EOF
     - ssh-keyscan -t rsa ${CI_SERVER_HOST} > ~/.ssh/known_hosts
     ## ssh-keyscan doesn't support proxies so we can't fetch the fingerprint online
     - |
       cat <<EOF >> ~/.ssh/known_hosts
       # ssh.github.com:443 SSH-2.0-babeld-2e9d163d
       [ssh.github.com]:443 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
       EOF
     - cat ~/.ssh/config



build:
    cache: {}
    stage: build
    artifacts:
      expire_in: 1 day
      paths:
      - app/build/outputs/apk
    script:
        - echo 123
    when: manual

sync-app:
    cache: {}
    stage: mirror
    only:
        refs:
          - master
    artifacts:
      expire_in: 1 day
      paths:
      - log.txt
    script:
        - git clone git@gitlab.protontech.ch:agarroux/publish-github.git
        - ./publish-github/sync commit --private-url $CI_REPOSITORY_URL --public-url "$PUBLIC_REPO_URL"

sync-release:
    cache: {}
    stage: public-release
    needs: [build]
    only:
        refs:
          - tags
    artifacts:
      expire_in: 1 day
      paths:
      - log.txt
      - request-create-curl.json
    script:
        - git clone git@gitlab.protontech.ch:agarroux/publish-github.git
        - ./publish-github/sync tag --private-url $CI_REPOSITORY_URL --public-url "$PUBLIC_REPO_URL"
        - ./publish-github/release generate --app android-pvpn --github-repo "$(echo $PUBLIC_REPO_URL | sed -rn 's/.+:(.+)\.git/\1/p')" --github-token "$GITHUB_ACCESS_TOKEN"

variables:
  PUBLIC_REPO_URL: git@github.com:dhoko/synctest.git
