stages:
    - mirror

include:
  - project: 'proton/fe/proton-config'
    ref: master
    file: '/_templates-ci/config.gitlab-ci.yml'

sync-app:
    cache: {}
    stage: mirror
    only:
        refs:
          - tags
          - master

    script:
        # Clone instead of using the current CI as it creates the error (shallow update not allowed)
        - git clone "$CI_REPOSITORY_URL" --branch master _APP_CLONE;
        - cd _APP_CLONE
        - git remote add public $PUBLIC_REPO_URL
        - git push public master
        # Push the latest tag we can find
        - git push public "$(git describe --abbrev=0)"

variables:
  PUBLIC_REPO_URL: git@github.com:dhoko/synctest.git
